name: tests

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install a service for test and list
        run: |
          touch counter_test.service
          echo -e "[Unit]\nDescription=Test\nAfter=multi-user.target\n\n" >> counter_test.service
          echo -e "[Service]\nType=simple\n" >> counter_test.service
          echo -e "ExecStart=python3 -c \"while True: print('1'); import time; time.sleep(1)\"\n >> counter_test.service
          echo -e "[Install]\nWantedBy=multi-user.target" >> counter_test.service
          cp counter_test.service /etc/systemd/system/counter_test.service
          systemctl daemon-reload
          sudo systemctl list-units --type=service --all
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install ruff pytest
          pip install coveralls
      - name: Test with pytest
        run: |
          coverage run -m pytest tests/
      - name: Upload coverage data to coveralls.io
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.test-name }}
          COVERALLS_PARALLEL: true
  coveralls:
    name: Indicate completion to coveralls.io
    needs: build
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --service=github --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}